"""Contract for a separately implemented and tested emulator adapter.
No arbitrary memory addresses are written by this project.
Implement this interface for a known game build, using its emulator's supported API.
"""
from typing import Protocol


class GameAdapter(Protocol):
    def version_matches(self, iso_sha256: str, game_version: str) -> bool: ...
    def read_player(self) -> dict[str, float]: ...
    def set_remote_player(self, peer_id: str, position: dict[str, float]) -> None: ...
    def take_over_npc(self, npc_id: str, controller_id: str) -> None: ...
    def release_npc(self, npc_id: str) -> None: ...
    def set_modifier(self, modifier: str, duration_seconds: float) -> None: ...
    def save_state(self) -> bytes: ...
    def load_state(self, data: bytes) -> None: ...
